### ISSUE TITLE
Unable to get report output

### ISSUE THREAD

**Issue by NtHawk101** [Sy14r/Cryptbreaker#6]
Desktop Docker version: 2.2.0.3 (42716)
Cryptbreaker version 1.1
Infrastructure environment: Maybe 15 users counting service accounts (lab environment - VMware)
OS: Windows Server 2019

I loaded the zipped data from the export of ntdsutil and that took longer than I expected. (10 minutes)
Clicked 'attempt to crack', received the 'retrieving price data' dialog and then it hangs and never gets past that point.
The display shows the following:
Hashes cracked: 0
Different Hashes: 57
Total Hashes: 158

PowerShell (Docker) window states  level=error msg="error waiting for container: EOF" and then reverted to the system32 prompt.

Demo looks like an awesome program. Any help would be appreciated.

**Comment by Sy14r** [comment]
I’ll take a look at this in the morning and get back to you.

Thanks for the report.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Sy14r** [comment]
Good Morning,

I was unable to recreate the issue. On my Windows box the ZIP upload/extract took ~1 minute and the cracking worked as expected.

That being said, I can think of one or two things that might help me figure this out more. Currently, Cryptbreaker expects a set file structure in the ZIP that you upload (a future feature is to be more flexible with file structure.) 

The structure for your Zip should currently be as follows to guarantee everything works as expected (quick tree view and screenshots for clairty)

Let me know if that helps

```
Test.zip
├───Active Directory
│       ntds.dit
│
└───registry
        SECURITY
        SYSTEM
```
Zip Name (whatever you want.zip)
![image](https://user-images.githubusercontent.com/18131018/74934831-a8d17100-53ac-11ea-9af9-502dfef63cbb.png)

![image](https://user-images.githubusercontent.com/18131018/74934844-b4249c80-53ac-11ea-8e61-77d615e3eb47.png)

![image](https://user-images.githubusercontent.com/18131018/74934862-bedf3180-53ac-11ea-80a4-be29f20894a6.png)

**Comment by NtHawk101** [comment]
I was able to get past this issue. The zip file was a winrar zip. I witched to 7zip and it worked. Please close this issue. I have a different issue that I will open a separate issue for.
