### ISSUE TITLE
Azure Support?

### ISSUE THREAD

**Issue by grease082** [Sy14r/Cryptbreaker#9]
Hi, will there be Azure support in the near future? Or is it possible to use it in an Azure cloud environment?

**Comment by Sy14r** [comment]
Hello,

As of now there are no immediate plans to add Azure support. One of the key features in AWS that Cryptbreaker utilizes is _spot pricing_ which allows you to use compute resources at significantly reduced costs. Azure just started testing this feature in their environment in December 2019. Once it's more mature if the need is there we may add support to 'choose your cloud' but for now that isn't a priority for the project.

It is open source and if someone else adds that support I'll be happy to review it and bring it into our project but I don't anticipate that happening anytime soon.
